# name属性用来指定这个工作流的名字

name: 部署文档

# 这个部分用来指定能够触发工作流执行的事件
on:
  # 当对分支main进行push操作的时候，这个工作流就被触发了
  push:
    branches: [push-docs]
  pull_request:
    branches: [push-docs]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流是由一个或多个的jobs构成的，在jobs里来说明要交给GitHub aciton执行的任务
jobs:
  # 这个jobs中的一个任务，名字叫build(随便怎么取)
  build:
    # 用来指定这个任务在什么操作系统上跑(服务器是GitHub免费提供的)
    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [14.x]

    # 指出这个build任务的步骤
    steps:
      - uses: actions/checkout@master

      - name: 初始化node环境
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 安装yarn
        run: npm i -g yarn

      - name: 安装依赖
        run: yarn

      - name: 设置ssk
        env:
          ACCESS_TOKEN: ${{ secrets.DOCS_TOKEN }}
        #  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACCESS_TOKEN" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "bhabgs@aliyun.com"
          git config --global user.name "bhabgs"

      - name: 开始推送文档
        run: yarn docs:push

      - name: 部署通知
        run: echo 文档部署成功，请访问 https://bhabgs.github.io/vite-vui-docs/
