name: 发布ui

on:
  push:
    branches: [deploy-vui]
jobs:
  publish:
    name: 发布ui工作流
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    # 指出这个build任务的步骤
    steps:
      - uses: actions/checkout@v1

      - name: 初始化node环境
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: 安装yarn
        run: npm i -g yarn

      - name: 安装依赖
        run: yarn

      - name: 编译部署util
        working-directory: 'package/vitevuu'
        run: yarn build

      - name: publish
        working-directory: 'package/vitevui'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish

      - name: publish 成功通知
        run: echo npm vui 推送成功，请访问 https://bhabgs.github.io/vite-vui-docs/
      
      - name: github-release
        working-directory: 'package/vitevui'
        - run: npm i -g github-release-from-changelog
        - run: npm run genlog
        - run: github-release-from-changelog
          env:
            GITHUB_TOKEN: ${{secrets.PERSONAL_TOKEN}}

